name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    
    - name: Restore api key
      env: 
        GRADLE_PROPERTIES: ${{secrets.GRADLE_PROPERTIES}}
      shell: bash
      run: |
        mkdir -p ~/.gradle/
        echo "${GRADLE_PROPERTIES}" > ~/.gradle/gradle.properties
          
    - name: set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
